backend:
  name: git-gateway
  branch: main

media_folder: "img/maquinaria"
public_folder: "img/maquinaria"

collections:
  - name: "maquinas"
    label: "Maquinaria en Venta"
    folder: "_maquinas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre de la máquina", name: "title", widget: "string" }
      - { label: "Precio (€)", name: "precio", widget: "string" }
      - { label: "Foto principal", name: "image", widget: "image" }
      - { label: "Descripción detallada", name: "body", widget: "markdown" }
